DROP DATABASE IF EXISTS snowflake_db;
CREATE DATABASE snowflake_db;

DROP SCHEMA IF EXISTS staging;
CREATE SCHEMA staging;

DROP SCHEMA IF EXISTS ods;
CREATE SCHEMA ods;

DROP SCHEMA IF EXISTS dwh;
CREATE SCHEMA dwh;
